# Generated by Django 3.2.8 on 2021-11-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=5000)),
                ('email', models.CharField(default='', max_length=5000)),
                ('address', models.CharField(default='', max_length=5000)),
                ('city', models.CharField(default='', max_length=5000)),
                ('state', models.CharField(default='', max_length=5000)),
                ('zip_code', models.CharField(default='', max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contacts'},
        ),
    ]
